Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.insert_key = false
  config.vm.hostname = "ab-logstash"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 3072
    v.cpus = 2
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "vv"
  end
end