Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 2812, host: 22813
  config.vm.network "forwarded_port", guest: 5000, host: 25000
  config.vm.network "forwarded_port", guest: 9100, host: 29100
  config.vm.network "forwarded_port", guest: 9200, host: 29200
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "vv"
  end
end