---
- name: Update and Upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: "{{ apt_update_cache_valid_time }}"

- name: Install packages
  apt:
    name: "{{ apt_install }}"
    state: "{{ apt_install_state }}"

- name: Add Elastic apt key
  apt_key:
    url: "{{ elastic_url }}/{{ elastic_key }}"
    state: "{{ elastic_state }}"

- name: Add Elastic repository
  apt_repository:
    repo: 'deb {{ elastic_url }}/packages/{{ elastic_version }}/apt stable main'
    state: "{{ elastic_state }}"
    update_cache: true
