---
- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch.
  template:
    src: "elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ es_host }}"
    port: "{{ es_port }}"
    delay: 3
    timeout: 600

- name: Install discovery-ec2
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install -b discovery-ec2

- name: Install elasticsearch-head
  shell:
    cmd: |
      git clone git://github.com/mobz/elasticsearch-head.git
      cd elasticsearch-head
      npm install

- name: Enable elasticsearch-head
  shell: cd /home/vagrant/elasticsearch-head && nohup npm run start > /dev/null 2>&1 &

- name: Install elasticsearch plugin - elasticsearch-HQ
  block:
    - name: Clone repo
      shell: git clone https://github.com/ElasticHQ/elasticsearch-HQ
    - name: Install requirements
      pip:
        requirements: /home/vagrant/elasticsearch-HQ/requirements.txt

- name: Enable elasticsearch plugin - elasticsearch-HQ
  shell: nohup python3 /home/vagrant/elasticsearch-HQ/application.py > /dev/null 2>&1 &


