Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04.6-amd64-virtualbox.box"
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.network "forwarded_port", guest: 22, host: 22022, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 22080
  config.vm.network "forwarded_port", guest: 443, host: 22443
  config.vm.network "forwarded_port", guest: 3306, host: 22306
end