Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04.6-amd64-virtualbox.box"
  config.ssh.insert_key = false
  config.vm.provision 'chef_solo' do |chef|
    chef.arguments = "--chef-license accept"
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "nginx"
    chef.add_recipe "java"
    chef.add_recipe "mysql"
    chef.add_recipe "tomcat"
  end
end