---
- name: Start monit service
  systemd:
    name: monit.service
    state: started
- name: Configure UI
  lineinfile:
    path: /etc/monit/monitrc
    line: "set httpd port 2812 and allow admin:monit"
- name: Restart monit service
  systemd:
    name: monit.service
    state: restarted
- wait_for:
    port: 2812